// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace InsertDateTime
{
    internal sealed partial class Vsix
    {
        public const string Id = "8def4441-acfd-4dd6-bffd-4531a57dee37";
        public const string Name = "Insert DateTime";
        public const string Description = @"一键插入yyyyMMddHH:mm:ss时间格式VS扩展 ";
        public const string Language = "en-US";
        public const string Version = "1.2";
        public const string Author = "Mads Kristensen";
        public const string Tags = "";
    }
}
