// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace InsertDateTime
{
    using System;

    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidInsertDateTimePackageString = "50121d57-9e96-4986-becb-fe05620e79a8";
        public static Guid guidInsertDateTimePackage = new Guid(guidInsertDateTimePackageString);

        public const string guidInsertDateTimeCmdSetString = "2440eeb0-81f7-4062-b88a-99ca97249e33";
        public static Guid guidInsertDateTimeCmdSet = new Guid(guidInsertDateTimeCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int cmdInsertDateTime = 0x0100;
    }
}